### ISSUE TITLE
Trigger for activity generation

### ISSUE THREAD

**Issue by bvlj** [LuCEresearchlab/expression-tutor-activity-generator#1]
On ~~release~~ tag.

Then we need to have a script to create tags for all repositories.

It has been observed how, if one targets "release creation" instead of "tag creation", actions are triggered twice if a tag is created alongside the release (which is the most common use case scenario for us).

Reference:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
- https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#create-a-tag-object
- https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

**Comment by hauswirth** [comment]
Ideally the teaching team could manually trigger activity generation for all repos of a lab (activity group?) at once.

Schedule seems too rigid to me (it's hard to predict, there always are exceptions and delays).

If release could be triggered globally, for all repos of a lab (activity group?), e.g., via a script that talks to GitHub, then I think that would be the way to go. (If release requires the teaching team or the students to manually trigger releases for each repo, that would be painful.)
